services:
  backend:
    build: ./backend
    ports:
      - 5000:5000
    restart: always
    environment:
      PYTHONUNBUFFERED: 1
    depends_on:
      - mongo

  mongo:
    image: mongo
    restart: always
    ports:
      # for debugging
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet

  # web interface, remove when publish
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:123456@mongo:27017/
